name: Macguffin2
version: 2.0.4
main: gay.realmromp.macguffin2.Macguffin2
description: hopefully it works this time around
author: Willow Leverone
website: https://discord.gg/uuYRe6BUSh
api-version: 1.19
load: POSTWORLD
commands:
  sniff:
    description: Check if the egg is nearby
    usage: /sniff
    permission: macguffin2.sniff
  state:
    description: checks the egg state
    usage: /state
    permission: macguffin2.state
permissions:
  macguffin2.sniff:
    description: Allows use of the sniff command
    default: true
  macguffin2.state:
    description: Allows use of the state command
    default: op