name: Macguffin2
version: 2.0.1
main: gay.realmromp.macguffin2.Macguffin2
description: hopefully it works this time around
author: Willow Leverone
website: https://discord.gg/uuYRe6BUSh
api-version: 1.19
load: POSTWORLD